# Generated by Django 3.0.7 on 2020-06-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default='0')),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
